[package]
name = "pubsub_zmq"
version = "0.1.0"
authors = ["yubo <anhuitianyu@163.com>"]
edition = "2018"

[dependencies]
cita-logger = "0.1.1"
crossbeam-channel = "0.4.2"
lazy_static = "1.4"
zmq = "0.9.2"

[features]
default = ["vendored-zmq"]
vendored-zmq = ['zmq/vendored']